version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "update-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b2wdppd2eejm"
s3_prefix = "update-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
